Parameters:
    KeyPair:
      Description: Use this keypair to SSH into the instances
      Type: AWS::EC2::KeyPair::KeyName
Resources:
    MyVpc:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
    Subnet1:
      Type: AWS::EC2::Subnet
      Description: Create Subnet1 for placing EC2 server1
      Properties:
        VpcId: !Ref MyVpc
        CidrBlock: 10.0.1.0/24
        AvailabilityZone: "ap-southeast-2a"
        Tags:
          Keys: Application
          Value: !Ref "AWS::StackId"
    Subnet2:
      Type: AWS::EC2::Subnet
      Description: Create Subnet2 for placing EC2 server2
      Properties:
        VpcId: !Ref MyVpc
        CidrBlock: 10.0.2.0/24
        AvailabilityZone: "ap-southeast-2b"
        Tags:
          Keys: Application
          Value: !Ref "AWS::StackId"
    Subnet3:
      Type: AWS::EC2::Subnet
      Description: Create Subnet3 to have the ELB and other systems which are internet facing
      Properties:
        VpcId: !Ref MyVpc
        CidrBlock: 10.0.3.0/24
        AvailabilityZone: "ap-southeast-2a"
        Tags:
         Keys: Application
         Value: !Ref "AWS::StackId"
    InternetGateway:
       Type: AWS::EC2::InternetGateway
       Properties:
        Tags:
          Keys: Application
          Value: !Ref "AWS::StackId"
    AttachGateway:
       Type: AWS::EC2::VPCGatewayAttachment
       Properties:
        VpcId: !Ref MyVpc
        InternetGatewayId: !Ref InternetGateway
    RouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref MyVpc
        Tags:
         Keys: Application
         Value: !Ref "AWS::StackId"
    Route:
      Type: AWS::EC2::Route
      DependsOn: "AttachGateway"
      Properties:
        RouteTableId: !Ref AttachGateway
        DestinationCidrBlock: "0.0.0.0/0"
        GatewayId: !Ref InternetGateway
    SubnetRouteTableAssociation:
      Type: AWS:EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId: !Ref Subnet3
        RouteTableId: !Ref RouteTable